"""Cold-outreach draft approval state machine (Slice 1).

Every draft moves through a small set of explicit states. Only a
HUMAN can transition into `approved_to_send`; everything else is
either system-driven (initial seed, automatic invalidation) or
operator-driven (rejection, re-queue).

States
------
needs_review
    Initial state on every newly-inserted draft. Stage 7 produces
    this; the operator's review queue surfaces it; deliverability /
    relationship blockers attach as metadata but do NOT auto-promote.

approved_to_send
    A HUMAN explicitly approved this exact (subject + body) hash.
    Gmail / Attio sync / send_queue.csv read ONLY this state.

rejected
    A HUMAN explicitly rejected the draft. Doesn't reach the send
    queue. Operator may un-reject (rejected -> needs_review).

stale_after_approval
    A previously-approved draft has been invalidated by an automatic
    trigger (see INVALIDATION_TRIGGERS below). The send queue must
    drop the draft until a human re-approves. Re-running Stage 7 on
    the same partner-id produces a NEW draft row (incrementing
    regeneration_count); the old approved row flips to stale.

sent
    Terminal state: Gmail / outreach has confirmed delivery (or the
    Attio sync produced an outreach_status moving past
    'ready_to_send'). Does not transition further; reply / passed /
    meeting outcomes land in the outcomes table instead.

Allowed transitions
-------------------
The table below is the ONLY allowed edge set. Anything else is a
state-machine violation and raises InvalidApprovalTransition.

  (initial)            -> needs_review
  needs_review         -> approved_to_send       (human)
  needs_review         -> rejected               (human)
  needs_review         -> stale_after_approval   (system: regenerated)
  approved_to_send     -> stale_after_approval   (system: invalidated)
  approved_to_send     -> rejected               (human: changed mind)
  approved_to_send     -> sent                   (system: delivered)
  rejected             -> needs_review           (human: re-queue)
  stale_after_approval -> needs_review           (human: re-queue)
  stale_after_approval -> approved_to_send       (human: re-approve)

Invalidation triggers (system -> stale_after_approval)
------------------------------------------------------
An approved draft becomes stale when ANY of these happen:

  - the canonical draft_hash (subject + body) changes (regeneration
    or human edit produced a new body)
  - the partner's email changes after approval (the recipient is no
    longer who was approved)
  - do_not_contact is set on the partner
  - the partner's relationship_status moves to
    {passed, do_not_contact, invested}
  - the partner's composite_fit_score or recommended_to_send flag
    materially changes via Stage 6 re-run

Each trigger writes a `stale_after_approval` event with
notes=<trigger reason> so the operator can see WHY the prior approval
was invalidated.
"""
from __future__ import annotations

from typing import Final


# State names. Use these constants everywhere rather than string
# literals so a typo becomes an ImportError, not a silent bug.
STATE_NEEDS_REVIEW: Final[str] = "needs_review"
STATE_APPROVED_TO_SEND: Final[str] = "approved_to_send"
STATE_REJECTED: Final[str] = "rejected"
STATE_STALE_AFTER_APPROVAL: Final[str] = "stale_after_approval"
STATE_SENT: Final[str] = "sent"

ALL_STATES: Final[frozenset[str]] = frozenset({
    STATE_NEEDS_REVIEW,
    STATE_APPROVED_TO_SEND,
    STATE_REJECTED,
    STATE_STALE_AFTER_APPROVAL,
    STATE_SENT,
})

# States that allow the draft into the SEND queue. Gmail /
# scripts/08_sync_to_attio.py / send_queue.csv read this set.
APPROVED_STATES: Final[frozenset[str]] = frozenset({
    STATE_APPROVED_TO_SEND,
})

# States that appear in the REVIEW queue (operator action needed).
REVIEWABLE_STATES: Final[frozenset[str]] = frozenset({
    STATE_NEEDS_REVIEW,
    STATE_STALE_AFTER_APPROVAL,
})

# Terminal states -- no further transitions allowed.
TERMINAL_STATES: Final[frozenset[str]] = frozenset({
    STATE_SENT,
})


# Allowed transitions. Maps (from_state, to_state) -> action source.
# 'human' edges require an operator action (CLI / UI); 'system'
# edges are auto-generated by the pipeline. Stage 7's initial seed
# is the special (None -> needs_review) edge.
_TRANSITIONS: Final[dict[tuple[str | None, str], str]] = {
    (None, STATE_NEEDS_REVIEW): "system",
    (STATE_NEEDS_REVIEW, STATE_APPROVED_TO_SEND): "human",
    (STATE_NEEDS_REVIEW, STATE_REJECTED): "human",
    (STATE_NEEDS_REVIEW, STATE_STALE_AFTER_APPROVAL): "system",
    (STATE_APPROVED_TO_SEND, STATE_STALE_AFTER_APPROVAL): "system",
    (STATE_APPROVED_TO_SEND, STATE_REJECTED): "human",
    (STATE_APPROVED_TO_SEND, STATE_SENT): "system",
    (STATE_REJECTED, STATE_NEEDS_REVIEW): "human",
    (STATE_STALE_AFTER_APPROVAL, STATE_NEEDS_REVIEW): "human",
    (STATE_STALE_AFTER_APPROVAL, STATE_APPROVED_TO_SEND): "human",
}


# Trigger names for stale_after_approval events. Persistence layer
# accepts these as `notes` prefixes so the audit reads cleanly.
TRIGGER_BODY_REGENERATED: Final[str] = "body_regenerated"
TRIGGER_EMAIL_CHANGED: Final[str] = "partner_email_changed"
TRIGGER_DO_NOT_CONTACT_SET: Final[str] = "do_not_contact_set"
TRIGGER_RELATIONSHIP_CHANGED: Final[str] = "relationship_changed"
TRIGGER_SCORE_MATERIALLY_CHANGED: Final[str] = "score_materially_changed"


class InvalidApprovalTransition(ValueError):
    """Raised when a caller attempts a (from, to) edge that's not in
    the allowed transition table. Includes both endpoints so the
    operator can see what went wrong.
    """

    def __init__(self, from_state: str | None, to_state: str) -> None:
        self.from_state = from_state
        self.to_state = to_state
        super().__init__(
            f"approval state transition {from_state!r} -> {to_state!r} "
            f"is not allowed; see core.approval.state_machine for the "
            f"transition table."
        )


def is_terminal(state: str) -> bool:
    """A draft in a terminal state cannot transition further. Used by
    the persistence layer to refuse spurious updates."""
    return state in TERMINAL_STATES


def is_approved(state: str) -> bool:
    """Used by Gmail / Attio / send_queue readers to gate which
    drafts they pick up. Centralized so a future tweak (e.g.
    distinguishing approved_to_send from approved_with_warning)
    lands in one place."""
    return state in APPROVED_STATES


def is_reviewable(state: str) -> bool:
    """The review-queue CSV / UI filters on this. Includes both
    fresh `needs_review` and `stale_after_approval` (the latter
    needs a human to either re-approve or re-queue)."""
    return state in REVIEWABLE_STATES


def assert_can_transition(
    from_state: str | None, to_state: str, *, source: str | None = None,
) -> str:
    """Validate that the edge is allowed. Returns the expected
    action source ('human' | 'system'). When `source` is supplied,
    additionally verify that the caller's actor type matches what
    the edge requires -- e.g. a CLI script calling with source='human'
    on a system-only edge (regeneration) is a bug.

    Raises InvalidApprovalTransition on a disallowed edge.
    """
    if to_state not in ALL_STATES:
        raise InvalidApprovalTransition(from_state, to_state)
    edge = (from_state, to_state)
    if edge not in _TRANSITIONS:
        raise InvalidApprovalTransition(from_state, to_state)
    expected_source = _TRANSITIONS[edge]
    if source is not None and source != expected_source:
        raise InvalidApprovalTransition(from_state, to_state)
    return expected_source


def allowed_next_states(from_state: str | None) -> set[str]:
    """Helper for UIs / CLIs that show 'what can I do from here?'."""
    return {
        to_s for (f, to_s) in _TRANSITIONS.keys() if f == from_state
    }
