window.MOCK_PIPELINE = {
  counts: {
    funds: 184,
    partners: 612,
    verifiedSignals: 1438,
    recommended: 18,
    ready: 9,
    blocked: 3,
  },
  gates: [
    {
      level: "block",
      title: "Stage 7 is stale",
      detail: "Stage 6 completed after the latest email batch. Regenerate drafts before exporting.",
      action: "Run Stage 7 after Claude's refactor lands",
    },
    {
      level: "warn",
      title: "3 partners missing email",
      detail: "They can stay in review, but Gmail draft creation should skip them.",
      action: "Collect emails or mark warm path needed",
    },
  ],
  runbook: [
    {
      status: "done",
      title: "Configure workspace",
      command: "$EDITOR clients/northstar_seed/config/*.yaml",
      detail: "Company, raise context, axes, required systems, and source lists are filled in.",
    },
    {
      status: "done",
      title: "Ingest and enrich",
      command: "uv run scripts/01_aggregate_sources.py && uv run scripts/02_enrich_funds.py",
      detail: "Fund list and partner roster are present. Seven fund pages skipped as optional.",
    },
    {
      status: "review",
      title: "Resolve attribution review",
      command: "uv run scripts/list_ambiguous_matches.py",
      detail: "Stage 3 has ambiguous matches that should be reviewed before final scoring.",
    },
    {
      status: "blocked",
      title: "Regenerate email batch",
      command: "uv run scripts/07_generate_emails.py --top 10",
      detail: "Blocked until Claude finishes the Stage 7 refactor and Stage 6 freshness clears.",
    },
    {
      status: "locked",
      title: "Sync or draft outbound",
      command: "uv run scripts/08_sync_to_attio.py --require-ready-to-send",
      detail: "Disabled in the prototype. In the real app this unlocks only after run locks and production policy exist.",
    },
  ],
  setupChecklist: [
    { label: "Anthropic key configured", state: "done" },
    { label: "Attio marked required for production", state: "done" },
    { label: "Gmail intentionally disabled for pilot", state: "warn" },
    { label: "Run lock not landed yet", state: "blocked" },
    { label: "Stage 7 freshness stale", state: "blocked" },
  ],
  setupSteps: [
    { name: "Raise Profile", state: "done", summary: "Company, round, target check size, timing, and traction are filled in." },
    { name: "Investor Targeting", state: "done", summary: "Seed and Series A funds with vertical SaaS and applied AI theses." },
    { name: "Outreach Rules", state: "review", summary: "Warm-intro preference set, but cold email risk still needs confirmation." },
    { name: "Connections", state: "warn", summary: "Apollo import planned; Attio and Gmail stay dry-run for first pass." },
    { name: "Advanced Sources", state: "optional", summary: "File upload and source URLs can be added after the raise profile is saved." },
    { name: "Production Policy", state: "blocked", summary: "Run lock and Stage 7 freshness still blocking live actions." },
  ],
  setupWorkflow: {
    currentStep: "Raise Profile",
    profile: {
      company: "Northstar Systems",
      website: "northstar.example",
      round: "Seed",
      targetRaise: "$2.5M",
      firstClose: "45 days",
      location: "New York, remote-first",
      oneLiner: "Decision workflow software for pricing teams that need to turn messy market inputs into daily actions.",
      traction: "11 design partners, 3 paid pilots, and weekly active use across revenue, finance, and ops teams.",
      customer: "Mid-market B2B companies with pricing complexity and high-volume quoting workflows.",
      whyNow: "Teams are adding AI analytics, but still make pricing decisions in spreadsheets and Slack.",
    },
    investorFit: {
      stages: ["Seed", "Pre-seed", "Series A"],
      checkSize: "$250K-$1M",
      geographies: ["US", "Canada", "UK"],
      thesisTags: ["vertical SaaS", "applied AI", "workflow automation", "pricing", "revenue operations"],
      avoid: ["growth-only funds", "crypto-only funds", "consumer-only funds"],
    },
    outreachPolicy: [
      { label: "Prefer warm intros when a mutual contact is known", state: "on" },
      { label: "Allow cold email only after email confidence is high", state: "on" },
      { label: "Block outreach to do-not-contact and prior pass records", state: "on" },
      { label: "Let the app send emails automatically", state: "off" },
    ],
  },
  inbox: [
    { type: "Ambiguous Match", severity: "block", owner: "Stage 3", item: "Aster Capital vs Astra Capital", next: "Resolve match before scoring" },
    { type: "Missing Email", severity: "warn", owner: "Review", item: "Dana Cole", next: "Add email or route warm intro" },
    { type: "Draft QA", severity: "block", owner: "Stage 7", item: "Renee Park", next: "Regenerate or reject draft" },
    { type: "Warm Path", severity: "review", owner: "Founder", item: "Kwame Boateng", next: "Ask Maya for intro" },
    { type: "Attio Conflict", severity: "warn", owner: "Stage 8", item: "Two people named Marcus Lindqvist", next: "Pick existing record" },
  ],
  emailEnrichment: {
    counts: {
      missing: 3,
      exported: 3,
      uploaded: 3,
      valid: 2,
      conflicts: 1,
    },
    exportColumns: [
      "partner_id",
      "partner_name",
      "fund_name",
      "fund_domain",
      "title",
      "linkedin_url",
      "send_now_priority",
      "recommended_to_send",
      "outreach_status",
    ],
    uploadColumns: [
      "partner_id",
      "partner_name",
      "fund_name",
      "email",
      "email_source",
      "confidence",
    ],
    rows: [
      {
        partnerId: "par_tidewater_dana",
        partner: "Dana Cole",
        fund: "Tidewater Capital",
        email: "dana@tidewater.example",
        source: "apollo",
        confidence: "high",
        status: "valid",
        issue: "",
      },
      {
        partnerId: "par_tidewater_renee",
        partner: "Renee Park",
        fund: "Tidewater Capital",
        email: "renee.park@gmail.com",
        source: "apollo",
        confidence: "medium",
        status: "review",
        issue: "Personal domain; confirm before outreach",
      },
      {
        partnerId: "par_meridian_alan",
        partner: "Alan Whitfield",
        fund: "Meridian Capital",
        email: "",
        source: "apollo",
        confidence: "none",
        status: "missing",
        issue: "Apollo returned no email",
      },
    ],
  },
  batches: [
    { id: "batch_20260524_0958", status: "current stale", ready: 9, qaFailed: 1, generated: "2026-05-24 09:58", note: "Generated before latest Stage 6 scoring" },
    { id: "batch_20260523_1812", status: "restorable", ready: 7, qaFailed: 0, generated: "2026-05-23 18:12", note: "Last fully passing review queue" },
    { id: "batch_20260523_1420", status: "archived", ready: 5, qaFailed: 2, generated: "2026-05-23 14:20", note: "Older prompt style; weaker hooks" },
  ],
  batchDiffs: [
    { metric: "Ready to send", current: "9", previous: "7", change: "+2" },
    { metric: "QA failed", current: "1", previous: "0", change: "+1" },
    { metric: "Missing email", current: "3", previous: "4", change: "-1" },
    { metric: "Warm intro needed", current: "2", previous: "1", change: "+1" },
  ],
  dryRun: {
    title: "Attio sync preview",
    summary: "9 records would be synced, 3 skipped, 1 conflict requires review.",
    blockers: ["Stage 7 batch is stale", "Run lock not active"],
    changes: [
      { record: "Priya Anand", object: "person", operation: "PATCH", fields: "draft, score, source evidence", risk: "low" },
      { record: "Northbeam Ventures", object: "company", operation: "PATCH", fields: "thesis, last activity", risk: "low" },
      { record: "Dana Cole", object: "person", operation: "SKIP", fields: "missing email", risk: "none" },
      { record: "Marcus Lindqvist", object: "person", operation: "CONFLICT", fields: "ambiguous match", risk: "review" },
    ],
  },
  stages: [
    { name: "01 Aggregate Sources", state: "ok", processed: 12, ok: 12, failed: 0, skipped: 0, last: "2026-05-24 08:04" },
    { name: "02 Enrich Funds", state: "ok", processed: 184, ok: 177, failed: 0, skipped: 7, last: "2026-05-24 08:21" },
    { name: "03 Mine Activity", state: "review", processed: 320, ok: 288, failed: 0, skipped: 32, last: "2026-05-24 08:48" },
    { name: "04 Partner Signals", state: "ok", processed: 412, ok: 392, failed: 0, skipped: 20, last: "2026-05-24 09:14" },
    { name: "05 Verify Quality", state: "ok", processed: 1660, ok: 1438, failed: 0, skipped: 222, last: "2026-05-24 09:40" },
    { name: "06 Score Candidates", state: "ok", processed: 612, ok: 548, failed: 0, skipped: 64, last: "2026-05-24 10:02" },
    { name: "07 Generate Emails", state: "stale", processed: 15, ok: 15, failed: 0, skipped: 0, last: "2026-05-24 09:58" },
    { name: "08 Sync Attio", state: "idle", processed: 0, ok: 0, failed: 0, skipped: 0, last: "never" },
  ],
  partners: [
    {
      id: "par_northbeam_priya",
      name: "Priya Anand",
      title: "Partner",
      fund: "Northbeam Ventures",
      domain: "northbeam.example",
      status: "ready_to_send",
      priority: 42.8,
      composite: 8.7,
      roundFit: 8.0,
      lead: 7.2,
      reach: 8.5,
      flags: ["qa_pass", "email_found"],
      hook: "Publicly argued that category workflow tools are moving from dashboard to decision layer.",
      source: "https://example.com/priya-category-workflows",
      subject: "Northbeam's decision-layer thesis",
      draft: "Priya - saw your note on workflow tools moving from dashboard to decision layer. That's the wedge we're building around: not another analytics surface, but the operating loop for teams making daily pricing decisions.\n\nWe're raising a seed round now and I think the timing maps to the pattern you described. Worth a focused conversation next week?",
      objection: "May think the category is too crowded.",
      preempted: true,
    },
    {
      id: "par_foundry_kwame",
      name: "Kwame Boateng",
      title: "General Partner",
      fund: "Foundry North",
      domain: "foundrynorth.example",
      status: "warm_path_needed",
      priority: 40.1,
      composite: 8.1,
      roundFit: 8.0,
      lead: 6.4,
      reach: 4.0,
      flags: ["warm_path", "qa_pass"],
      hook: "Repeatedly backs infrastructure products with early wedge traction.",
      source: "https://example.com/foundry-infra-note",
      subject: "Foundry's early infra pattern",
      draft: "Kwame - your recent seed checks seem to have a common thread: narrow infra wedge, real usage, then a broader system of record. That's close to how we're entering the market.\n\nWe're opening seed conversations and I wanted to see whether this is worth a short intro through Maya.",
      objection: "Needs warm intro.",
      preempted: false,
    },
    {
      id: "par_tidewater_dana",
      name: "Dana Cole",
      title: "Managing Director",
      fund: "Tidewater Capital",
      domain: "tidewater.example",
      status: "draft",
      priority: 37.6,
      composite: 7.6,
      roundFit: 8.0,
      lead: 5.0,
      reach: null,
      flags: ["missing_email", "unknown_reach"],
      hook: "Invests behind founder-led sales motion in vertical SaaS.",
      source: "https://example.com/tidewater-vertical-saas",
      subject: "Founder-led vertical SaaS",
      draft: "Dana - noticed your comments on founder-led sales as the early proof point in vertical SaaS. Our first wedge is built around that exact loop.\n\nWe're raising seed and I think the fit is specific enough to be worth a direct conversation.",
      objection: "No verified email yet.",
      preempted: false,
    },
    {
      id: "par_tidewater_renee",
      name: "Renee Park",
      title: "Partner",
      fund: "Tidewater Capital",
      domain: "tidewater.example",
      status: "qa_failed",
      priority: 35.4,
      composite: 7.1,
      roundFit: 7.5,
      lead: 5.6,
      reach: 5.0,
      flags: ["qa_failed", "personal_email_review"],
      hook: "Talks about vertical SaaS teams needing sharper implementation proof before seed.",
      source: "https://example.com/tidewater-implementation-proof",
      subject: "Implementation proof in vertical SaaS",
      draft: "Renee - noticed your comments on implementation proof as the real seed-stage filter in vertical SaaS.\n\nWe're raising seed now and our strongest early signal is usage from teams who already live inside the workflow we're replacing.",
      objection: "Draft has template-smell risk and personal email needs review.",
      preempted: false,
    },
    {
      id: "par_meridian_alan",
      name: "Alan Whitfield",
      title: "Principal",
      fund: "Meridian Capital",
      domain: "meridian.example",
      status: "email_missing",
      priority: 31.9,
      composite: 6.8,
      roundFit: 7.0,
      lead: 4.8,
      reach: null,
      flags: ["missing_email", "apollo_no_result"],
      hook: "Tracks applied AI workflow software but has not published a recent seed thesis.",
      source: "https://example.com/meridian-applied-ai-workflows",
      subject: "Applied AI workflow software",
      draft: "Alan - saw Meridian tracking applied AI workflow software, especially where teams get measurable operating leverage.\n\nWe're raising seed around that kind of workflow wedge and I wanted to check whether it fits your current focus.",
      objection: "No verified email from Apollo.",
      preempted: false,
    },
  ],
  reviewRows: [
    { partnerId: "par_northbeam_priya", partner: "Priya Anand", fund: "Northbeam Ventures", status: "ready_to_send", qa: "pass", priority: 42.8, issue: "" },
    { partnerId: "par_foundry_kwame", partner: "Kwame Boateng", fund: "Foundry North", status: "warm_path_needed", qa: "pass", priority: 40.1, issue: "Needs Maya intro" },
    { partnerId: "par_tidewater_dana", partner: "Dana Cole", fund: "Tidewater Capital", status: "draft", qa: "pass", priority: 37.6, issue: "Missing email" },
    { partnerId: "par_tidewater_renee", partner: "Renee Park", fund: "Tidewater Capital", status: "qa_failed", qa: "fail", priority: 35.4, issue: "Template smell high" },
  ],
  errors: [
    { when: "2026-05-24 09:47", stage: "03 Mine Activity", record: "techcrunch-feed", message: "Feed returned 403; marked optional in mock state" },
    { when: "2026-05-24 09:11", stage: "04 Partner Signals", record: "par_unknown", message: "Unknown partner id in content CSV" },
  ],
  states: [
    {
      title: "Empty Workspace",
      state: "empty",
      detail: "No funds imported yet. The UI should focus the operator on setup and Stage 1.",
      action: "Import funds",
    },
    {
      title: "Loading Health",
      state: "loading",
      detail: "Show stable skeleton rows so the layout does not jump while status loads.",
      action: "Waiting for status",
    },
    {
      title: "Config Error",
      state: "error",
      detail: "company.yaml has placeholders. The UI should show the exact file and field.",
      action: "Open setup checklist",
    },
    {
      title: "No Results",
      state: "empty",
      detail: "Search returned nothing. Offer to clear filters instead of showing a blank page.",
      action: "Clear filters",
    },
  ],
};
